---
- name: prepare to turn off service if required
  include_vars: off.yml
  when: filebeat_inputs == []

- name: prepare to turn on service if required
  include_vars: on.yml
  when: filebeat_inputs != []

- name: add elasticsearch repo
  yum_repository:
    name: elasticsearch-6.x
    description: Elastic repository for 6.x packages
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    enabled: yes
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: install latest filebeat package
  yum:
    pkg: filebeat
    state: "{{ filebeat_version_state | default('present') }}"
  when: ansible_os_family == 'RedHat'
  notify: ensure state of filebeat

- name: enable/disable filebeat services if necessary
  service:
    name: filebeat
    enabled: "{{ filebeat_enabled }}"
  when: ansible_os_family == 'RedHat'

- name: create filebeat inputs directory
  file:
    path: /etc/filebeat/inputs/
    state: directory

- name: write filebeat global config
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: ensure state of filebeat

- name: write filebeat inputs
  template:
    src: inputs.yml.j2
    dest: /etc/filebeat/inputs/{{ item.fields.type }}.yml
  with_items: "{{ filebeat_inputs }}"
  notify: ensure state of filebeat

- name: list required inputs
  set_fact:
    required_inputs: "{{ filebeat_inputs | map(attribute='fields.type') | list }}"

- name: list current inputs
  shell: ls -1 /etc/filebeat/inputs/ | grep yml | sed -e 's/\..*$//'
  register: current_inputs
  changed_when: false
  check_mode: no

- name: remove unused inputs
  file:
    path: /etc/filebeat/inputs/{{ item }}.yml
    state: absent
  with_items: "{{ current_inputs.stdout_lines }}"
  when: item not in required_inputs
  notify: ensure state of filebeat
